### PR TITLE
Finished hw03: to do list

### PR DESCRIPTION
**Pull request by Loquats**

### CODE REVIEW

**Comment by dandanbang** [comment]
Great work again Andy! Neat & clean code and everything works : )

**Comment by dandanbang** [comment]
Btw, are you enrolled on B Course?

**Comment by Loquats** [comment]
Hi Daniel. Yes, I am enrolled on BCourses, but my name on BCourses is "Yue Zhang". I got a BCourses message from the TA's about this name confusion and just replied.

**Comment by Loquats** [comment]
Sorry for the confusion!

**Pull request closed without merging**
